name: APK Builder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: JDK 8 Setup
        uses: actions/setup-java@v1
        
      - name: Grant rights
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 'Camera.apk'
          path: app/build/outputs/apk/release/app-release-unsigned.apk
