name: APK Builder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: JDK 8 Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8
        
      - name: Grant rights
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 'Camera'
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'app/build/outputs/apk/release/app-release-unsigned.apk'
          destination-github-username: 'LibertyPhoneProject'
          destination-repository-name: 'Vendor-GMS'
          target-directory: 'Camera/net.sourceforge.opencamera.apk'
          user-email: libbot@kuzoncode.com
          user-name: libbot
          target-branch: master
